# Generated by Django 4.0 on 2022-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='日文單字詞搜尋紀錄', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='查詢日期')),
            ],
        ),
    ]
